version: '3.6'
services:
  api:
    build:
      context: ../.
      dockerfile: ./docker/api/Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
  frontend:
    build:
      context: ../.
      dockerfile: ./docker/frontend/Dockerfile
    environment:
      - REDIS_URL=redis://redis1:6379
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - redis_network
      - default
  tracker:
    build:
      context: ../.
      dockerfile: ./docker/tracker/Dockerfile
    environment:
      - KAFKA_SERVER=kafka1:9092
      - REDIS_URL=redis://redis1:6379
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - kafka_network
      - redis_network
      - default
  consolidator:
    build:
      context: ../.
      dockerfile: ./docker/consolidator/Dockerfile
    environment:
      - KAFKA_SERVER=kafka1:9094
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - kafka_network
      - default
  pipeline:
    build:
      context: ../.
      dockerfile: ./docker/pipeline/Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
networks:
  kafka_network:
    name: kafka_external
    external: true
  redis_network:
    name: redis_network
    external: true