version: '3'
services:
  api:
    restart: unless-stopped
    ports:
      - 4001:4001
    env_file:
      - ../.env-prod
    environment:
      - NODE_ENV=production
  frontend:
    ports:
      - 4014:4014
    env_file:
      - ../.env-dev
    environment:
      - NODE_ENV=development
      - PORT=4014