version: '3'
services:
  api:
    ports:
      - 3001:3001
    env_file:
      - ../.env-dev
    environment:
      - NODE_ENV=development
      - PORT=3001
  frontend:
    ports:
      - 3014:3014
    env_file:
      - ../.env-dev
    environment:
      - NODE_ENV=development
      - PORT=3014
