version: '3.6'
services:
  api:
    image: jasony/revengine-api
    build:
      context: ../.
      dockerfile: ./docker/api/Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 4001:4001
    env_file:
      - ../.env-prod
    environment:
      - NODE_ENV=production
      - PORT=4001
    extra_hosts:
      - "rfvengine1:10.0.1.3"
      - "rfvengine2:10.0.1.4"
      - "rfvengine3:10.0.1.5"
      - "rfvengine4:10.0.1.6"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: start-first
  frontend:
    image: jasony/revengine-frontend
    build:
      context: ../.
      dockerfile: ./docker/frontend/Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    # networks:
    #   - redis_network
    #   - default
    ports:
      - 4014:4014
    env_file:
      - ../.env-prod
    environment:
      - NODE_ENV=production
      - PORT=4014
      - REDIS_URL=redis://redis1:6379
    depends_on:
      - api
      - redis1
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: start-first
  tracker:
    image: jasony/revengine-tracker
    build:
      context: ../.
      dockerfile: ./docker/tracker/Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - kafka_network
      - redis_network
      - default
    ports:
      - 4003:8080
    env_file:
      - ../.env-prod
    environment:
      - NODE_ENV=production
      - MMDB_FILE=/usr/lib/mmdb/dbip-city-lite-2024-02.mmdb
      - KAFKA_SERVER=kafka1:9092
      - REDIS_URL=redis://redis1:6379
      - PORT=8080
      - TRACKER_HOST=0.0.0.0
    depends_on:
      - api
      - kafka1
      - redis1
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: start-first
  consolidator:
    image: jasony/revengine-consolidator
    build:
      context: ../.
      dockerfile: ./docker/consolidator/Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - kafka_network
      - default
    env_file:
      - ../.env-prod
    environment:
      - NODE_ENV=production
      - KAFKA_SERVER=kafka1:9092
    depends_on:
      - api
      - kafka1
    # deploy:
    #   mode: global
  crossword_tracker:
    image: jasony/revengine-crossword-tracker
    build:
      context: ../.
      dockerfile: ./docker/crossword-tracker/Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - kafka_network
      - redis_network
      - default
    ports:
      - 4015:4015
    env_file:
      - ../.env-prod
    environment:
      - PORT=4015
      - NODE_ENV=production
      - MMDB_FILE=/usr/lib/mmdb/dbip-city-lite-2024-02.mmdb
      - KAFKA_SERVER=kafka1:9092
      - REDIS_URL=redis://redis1:6379
      - TRACKER_HOST=0.0.0.0
    depends_on:
      - api
      - kafka1
      - redis1
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: start-first
  listeners:
    image: jasony/revengine-listeners
    build:
      context: ../.
      dockerfile: ./docker/listeners/Dockerfile
    environment:
      - REDIS_URL=redis://redis1:6379
      - NODE_ENV=production
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - redis_network
      - default
    env_file:
      - ../.env-prod
    ports:
      - 4020:4020
      - 4021:4021
    depends_on:
      - api
      - kafka1
      - redis1
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: start-first
  wordpress_api:
    image: jasony/revengine-wordpress-api
    build:
      context: ../.
      dockerfile: ./docker/wordpress-api/Dockerfile
    environment:
      # - REDIS_URL=redis://redis1:6379
      - NODE_ENV=production
      - PORT=4030
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - redis_network
      - default
    env_file:
      - ../.env-prod
    ports:
      - 4030:4030
    depends_on:
      - api
      - redis1
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
        order: start-first
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - default
    restart: always
    volumes:
      - zookeeper-data:/var/lib/zookeeper
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    # deploy:
    #   mode: global
  kafka1:
    image: confluentinc/cp-kafka:7.4.4
    hostname: kafka1
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
    #   - external
      - default
    restart: always
    volumes:
      - kafka-data:/var/lib/kafka/data
    # deploy:
    #   mode: global
  redis1:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    # deploy:
    #   mode: global
    networks:
      - redis_network
      - default
    volumes:
      - redis-data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
networks:
  # kafka_network:
  #   name: kafka-swarm
  #   driver: overlay
  #   # external: true
  # redis_network:
  #   name: redis-swarm
  #   driver: overlay
  #   # external: true
  kafka_network:
    name: kafka-external
    external: true
  redis_network:
    name: redis-external
    external: true
volumes:
  kafka-data:
    driver: local
  redis-data:
    driver: local
  zookeeper-data:
    driver: local
