version: '3.6'
services:
  api:
    build:
      context: ../.
      dockerfile: ./docker/api/Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 4001:4001
    env_file:
      - ../.env-prod
    environment:
      - NODE_ENV=production
      - PORT=4001
    extra_hosts:
      - "rfvengine1:10.0.1.3"
      - "rfvengine2:10.0.1.4"
      - "rfvengine3:10.0.1.5"
      - "rfvengine4:10.0.1.6"
  frontend:
    build:
      context: ../.
      dockerfile: ./docker/frontend/Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - redis_network
      - default
    ports:
      - 4014:4014
    env_file:
      - ../.env-prod
    environment:
      - NODE_ENV=production
      - PORT=4014
      - REDIS_URL=redis://redis1:6379
    depends_on:
      - api
  tracker:
    build:
      context: ../.
      dockerfile: ./docker/tracker/Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - kafka_network
      - redis_network
      - default
    ports:
      - 4003:8080
    env_file:
      - ../.env-prod
    environment:
      - NODE_ENV=production
      - MMDB_FILE=/usr/lib/mmdb/dbip-city-lite-2024-02.mmdb
      - KAFKA_SERVER=kafka1:9092
      - REDIS_URL=redis://redis1:6379
    depends_on:
      - api
  consolidator:
    build:
      context: ../.
      dockerfile: ./docker/consolidator/Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - kafka_network
      - default
    env_file:
      - ../.env-prod
    environment:
      - NODE_ENV=production
      - KAFKA_SERVER=kafka1:9092
    depends_on:
      - api
  crossword_tracker:
    build:
      context: ../.
      dockerfile: ./docker/crossword-tracker/Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - kafka_network
      - redis_network
      - default
    ports:
      - 4015:4015
    env_file:
      - ../.env-prod
    environment:
      - PORT=4015
      - NODE_ENV=production
      - MMDB_FILE=/usr/lib/mmdb/dbip-city-lite-2024-02.mmdb
      - KAFKA_SERVER=kafka1:9092
      - REDIS_URL=redis://redis1:6379
      - TRACKER_HOST=0.0.0.0
    depends_on:
      - api
  listeners:
    build:
      context: ../.
      dockerfile: ./docker/listeners/Dockerfile
    environment:
      - REDIS_URL=redis://redis1:6379
      - NODE_ENV=production
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - redis_network
      - default
    env_file:
      - ../.env-prod
    ports:
      - 4020:4020
      - 4021:4021
    depends_on:
      - api
  wordpress_api:
    build:
      context: ../.
      dockerfile: ./docker/wordpress-api/Dockerfile
    environment:
      # - REDIS_URL=redis://redis1:6379
      - NODE_ENV=production
      - PORT=4030
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      # - redis_network
      - default
    env_file:
      - ../.env-prod
    ports:
      - 4030:4030
    depends_on:
      - api
networks:
  kafka_network:
    name: kafka-external
    external: true
  redis_network:
    name: redis-external
    external: true